export const QUESTION_CONSTANT = {
  GEN_QUESTION: 'genQuestions',
  STORE_ANSWER: 'storedAns',
  COUNT: 'count'
}

export const sampleQuestions = [
  "How would you introduce yourself to someone you've never met before?",
  'What is your daily routine on a weekday?',
  'Can you describe your favorite place in your hometown?',
  'What was your favorite vacation? Describe where you went and what you did.',
  'What are your plans for the next weekend?',
  'What is your favorite movie or book, and why do you like it?',
  'If you could travel anywhere in the world, where would you go and why?',
  'Imagine you lost your wallet. What steps would you take to find it or solve the problem?',
  'Compare the city life to the countryside. What are the advantages and disadvantages of each?',
  'If you could have any superpower, what would it be and how would you use it?',
  'What is your favorite hobby and why do you enjoy it?',
  'Describe your best friend. What makes them a great friend?',
  'What is the most interesting job you can think of, and why?',
  'Talk about a memorable event from your childhood.',
  'If you could meet any historical figure, who would it be and why?',
  'What is your favorite season of the year and why?',
  'Describe a book or movie that had a big impact on you.',
  'If you won a million dollars, what would you do with the money?',
  'What is your favorite dish and how do you prepare it?',
  'If you could change one thing about the world, what would it be and why?',
  'What is the last book you read or movie you watched, and what did you think of it?',
  'Describe an achievement you are proud of. Why does it mean a lot to you?',
  'If you could learn any new skill, what would it be and why?',
  'Describe a typical weekend for you.',
  'What is the most challenging thing you have ever done?',
  'If you could visit any period in history, when would it be and why?',
  "What are three things you can't live without and why?",
  'Talk about a time when you helped someone. How did you feel?',
  'What are your goals for the next five years?',
  'If you could have dinner with any fictional character, who would it be and why?',
  'Tell us about your favorite childhood memory.',
  'What would you do if you were the president of your country for a day?',
  'Describe the most beautiful place you have ever visited.',
  'What are some of your main goals in life?',
  'If you could have any job in the world, what would it be and why?',
  'Talk about a time when you faced a difficult challenge. How did you overcome it?',
  'What is your favorite form of entertainment (e.g., books, movies, sports) and why?',
  'If you could invent something new, what would it be and what problem would it solve?',
  'What qualities do you value most in a friend?',
  'Describe an interesting tradition or celebration in your culture.',
  'What is the most important lesson you have learned in life?',
  'Describe a time when you had to make a difficult decision. What did you choose and why?',
  'If you could go back in time, what advice would you give to your younger self?',
  'What is your favorite form of art (like painting, music, theater) and why?',
  'Talk about a book or movie that changed your perspective on a subject.',
  'If you could create a new holiday, what would it be and how would people celebrate it?',
  'What are some hobbies you would like to start and why?',
  'Describe your dream house. Where would it be and what features would it have?',
  'If you could be an expert in any field, what would it be and why?',
  'Describe a situation where you had to work in a team. What was your role and how did it go?',
  'Describe your favorite season and why you like it.',
  'What three words would you use to describe yourself and why?',
  'If you could witness any event in history, which one would you choose and why?',
  'What is your favorite animal and why?',
  'Tell us about a person who has had a significant impact on your life.',
  'If you could learn any musical instrument, which one would it be and why?',
  'What is the best piece of advice you have ever received?',
  'Describe a typical family celebration in your culture.',
  'If you could live anywhere in the world, where would it be and why?',
  'What does a perfect day look like to you?',
  'What was the last meal you cooked? Describe how you made it.',
  'If you could have a conversation with any person from history, who would it be and what would you ask them?',
  'What is your favorite sport or physical activity, and why do you enjoy it?',
  'Describe a significant cultural event or festival in your country.',
  'If you could change one aspect of your personality, what would it be and why?',
  'What is your dream job, and what makes it appealing to you?',
  'Describe a movie or a book that you didn’t like and explain why.',
  'If you could have one wish granted, what would it be and why?',
  'What is the most useful skill you have learned and how has it helped you?',
  'Talk about a memorable moment you experienced in a foreign country or a different city.',
  'What is the most interesting fact you know? How did you learn about it?',
  'If you could start a charity, what would it be for and why?',
  'Describe your favorite genre of music and why it appeals to you.',
  'If you could invent a new technology, what would it do?',
  'What is the best gift you have ever received and why was it special?',
  'If you could live in any fictional world, which one would you choose and why?',
  'What is the most important quality in a leader, in your opinion?',
  'Describe a recent dream you remember. What do you think it meant?',
  'If you could bring one famous person back to life, who would it be and why?',
  'What is your idea of a perfect vacation?',
  'Describe an unusual talent or hobby you have.',
  'If you could be a character in any book or movie, who would you be and why?',
  'What is your favorite childhood memory?',
  'If you could change one event in history, what would it be and why?',
  'Describe the last interesting conversation you had and what made it memorable.',
  'If you could have a conversation with an animal, which animal would you choose and what would you ask?',
  "What is the best piece of advice you've ever been given?",
  'Describe a custom or tradition from your country that others might find surprising.',
  'If you could spend a day with any fictional character, who would it be and what would you do?',
  "What is something you've always wanted to do but haven't yet? Why haven't you done it?"
]
